name: CI

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    name: Deploy code to Cloud Functions
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GCP Auth
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Cloud Functions Deploy ImportQrz
        uses: GoogleCloudPlatform/github-actions/deploy-cloud-functions@cf-action
        with:
          name: ImportQrz
          entry_point: ImportQrz
          runtime: go113
          env_vars: GCP_PROJECT=k0swe-kellog
