name: Test and Deploy main

on:
  push:
    branches:
      - main

jobs:

  test:
    name: Run unit tests
    strategy:
      matrix:
        go-version: [ 1.13.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

  deploy-ImportQrz:
    runs-on: ubuntu-latest
    name: Deploy ImportQrz to Cloud Functions
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GCP Auth
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Cloud Functions Deploy ImportQrz
        uses: GoogleCloudPlatform/github-actions/deploy-cloud-functions@master
        with:
          name: ImportQrz
          entry_point: ImportQrz
          runtime: go113
          env_vars: GCP_PROJECT=k0swe-kellog

  deploy-ImportLotw:
    runs-on: ubuntu-latest
    name: Deploy ImportLotw to Cloud Functions
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GCP Auth
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Cloud Functions Deploy ImportLotw
        uses: GoogleCloudPlatform/github-actions/deploy-cloud-functions@master
        with:
          name: ImportLotw
          entry_point: ImportLotw
          runtime: go113
          env_vars: GCP_PROJECT=k0swe-kellog
