name: Deploy

on:
  push:
    tags:
      - deploy

jobs:

  test:
    name: Run Golang unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

  deploy-golang-http:
    name: Deploy Golang HTTP
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        function-name: [ ImportQrz, ImportLotw, UpdateSecret ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GCP Auth
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Cloud Functions Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{ matrix.function-name }}
          entry_point: ${{ matrix.function-name }}
          runtime: go113
          env_vars: GCP_PROJECT=k0swe-kellog
          deploy_timeout: 900

  deploy-golang-pubsub:
    runs-on: ubuntu-latest
    name: Deploy Golang PubSub
    needs: test
    strategy:
      matrix:
        function-spec: [
          { name: FillNewQsoFromQrz, trigger: projects/k0swe-kellog/topics/contact-created }
        ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GCP Auth
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Cloud Functions Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{ matrix.function-spec.name }}
          entry_point: ${{ matrix.function-spec.name }}
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: ${{ matrix.function-spec.trigger }}
          runtime: go113
          env_vars: GCP_PROJECT=k0swe-kellog
          deploy_timeout: 900

  deploy-javascript:
    runs-on: ubuntu-latest
    name: Deploy Javascript Functions to Cloud Functions

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Firebase CLI
        run: npm i -g firebase-tools

      - name: Cache node deps
        uses: actions/cache@v2
        env:
          cache-name: cache-node-deps
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install deps
        working-directory: ./javascript/functions/
        run: npm install

      - name: Build & deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        working-directory: ./javascript/functions/
        run: npx firebase deploy --only functions --token "$FIREBASE_TOKEN"
