name: CI

on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy the code to Cloud Functions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GCP Auth
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Cloud Functions Deploy ImportQrz
        uses: GoogleCloudPlatform/github-actions/deploy-cloud-functions@cf-action
        with:
          name: ImportQrz
          entry_point: ImportQrz
          runtime: go113
