name: Test

on:
  push:
    branches-ignore:
      # Renovate branches will immediately become PRs
      - 'renovate/**'
    tags-ignore:
      - deploy
  pull_request:
    branches:
      - '**'

jobs:
  test-go:
    name: Build and test Golang functions
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: make build-go

  test-js:
    name: Build and test Javascript functions
    runs-on: ubuntu-latest

    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: make build-js
