name: Test

on:
  push:
    branches-ignore:
      # Renovate branches will immediately become PRs
      - 'renovate/**'
    tags-ignore:
      - deploy
  pull_request:
    branches:
      - '**'

jobs:
  test-go:
    name: Build and test Golang functions
    uses: k0swe/forester-func/.github/workflows/test-go.yml@main

  test-js:
    name: Build and test Javascript functions
    uses: k0swe/forester-func/.github/workflows/test-js.yml@main
